### ISSUE TITLE
Code optimization: manage chakra UI custom themes

### ISSUE THREAD

**Issue by dyannya** [ealfla8/ByteSized#37]
### Checklist
- [x] understand how extendTheme in chakraUI works
- [x] learn how to customize color themes within chakraUI

**Comment by NoahBres** [comment]
See: da0e093ec32af5659510e9b1f5e3f6d221c59883

I de-duped your theme-ing code by moving it up to the root Chakra provider. There was actually already an existing `<ChakraProvider>` in `_app.js`
This wraps the whole page, meaning we only need to modify this provider and attach the theme there to set the theme for the entire project.
